# Generated by Django 5.0 on 2023-12-24 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=50)),
                ('Physical_Address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MnEStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Phone_no', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Engagement_Name', models.CharField(max_length=50)),
                ('Engagement_Type', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contacts.address')),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_completed', models.DateField()),
                ('Due_Date', models.DateField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Posted_to_Department', to='contacts.address')),
                ('Engagement_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contacts.engagement')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Posted_to_Name', to='contacts.mnestaff')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=50)),
                ('Direct_Report', models.CharField(max_length=50)),
                ('Superior', models.CharField(max_length=50)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Posted_to_Address', to='contacts.address')),
            ],
        ),
        migrations.CreateModel(
            name='Posted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Posted_to_Designation', to='contacts.position')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Posted_to_Location', to='contacts.position')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Posted_to_Name', to='contacts.staff')),
                ('Phone_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Posted_to_Phone_No', to='contacts.staff')),
            ],
        ),
    ]
