# Generated by Django 5.0 on 2024-01-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posted',
            name='Phone_no',
        ),
    ]
